### ISSUE TITLE
zipping Python libraries

### ISSUE THREAD

**Issue by littleq0903** [natea/django-deployer#10]
Like some PaaS which have quota limitation of file amount, such as Google App Engine, in current roadmap, we will put the whole virtual environment into the project folder which will be entirely uploaded to the PaaS provider, that caused increasing of file amount.

We can compress each library to reduce the total number of files, then python still can import it from .zip files.

**Comment by natea** [comment]
This sounds like a great idea, although I think only GAE has this limitation. Can you point to some documentation for how to do this with GAE?

**Comment by littleq0903** [comment]
this is the feature of Python, not only on GAE.

Reference: [PEP 273](http://www.python.org/dev/peps/pep-0273/)

the only thing we need to do is compressing libs into one or more zip files, and put the file path into `sys.path`, then everything is set up.

BTW, after installing all requirements needed by paasbakeoff, my number of files comes up to 8245 totally.

while `appcfg.py update .`:
`Cloning 8245 application files.`

**Comment by littleq0903** [comment]
good news: the limitation of amount of blob or normal files is 10000 now.
bad news: paasbakeoff has almost totally 12000  : (

I can't do testing right now, I need to do this issue first.

**Comment by natea** [comment]
Maybe we can use this to reduce the number of uploaded files?
http://equallytrue.blogspot.com/2012/04/tutorial-handling-uploaded-zip-files.html

On Mon, Apr 1, 2013 at 5:44 AM, LittleQ (Colin Su) <notifications@github.com

> wrote:
> 
> good news: the limitation of amount of blob or normal files is 10000 now.
> bad news: paasbakeoff has almost totally 12000 : (
> 
> I can't do testing right now, I need to do this issue first.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/natea/django-deployer/issues/10#issuecomment-15710137
> .

## 

nate@appsembler.com
+1 (617) 517-4953
http://twitter.com/natea | http://linkedin.com/in/natea

**Comment by littleq0903** [comment]
no, we don't need that, precisely, we can not upload any files to GAE container, we store uploaded files in BlobStorage, which mean we store files in binary format but not files.

we just need to zip `site-packages`.

**Comment by littleq0903** [comment]
I found zipping files is not a good solution in GAE case, if we zip all dependencies, we can not access not .py file also, so like template files in mezzanine can not be accessed, so in this progress I won't adopt this approach.

but I've done deleting django and PIL part.
