### ISSUE TITLE
classifiers should include the specific python versions

### ISSUE THREAD

**Issue by willkg** [natea/django-deployer#21]
The classifiers list in setup.py has:

```
        "Programming Language :: Python",
```

But it should also include the specific Python versions this works with for better PyPI metadata.

If you know what versions it works with, I can throw together a PR.

**Comment by natea** [comment]
Hey Will, Thanks for the heads up. I've only tested it with Python 2.7, but I imagine that it'll work with 2.6 and 3.x. Most of the code is just using Fabric, so as long as Fabric works on those Python versions, django-deployer should as well.

**Comment by willkg** [comment]
Awesome! I'll do a PR for 2.7 since we know that's a known good now.

For 2.6 and 3.x, I'll figure out how to test it for sure. Maybe that'll result in tests, too.
