### ISSUE TITLE
some one of requirements in setup.py requires 'requests==0.14.2'

### ISSUE THREAD

**Issue by littleq0903** [natea/django-deployer#4]
the latest version of requests will assert Error.

possible reason:
- someone of the requirements requires 'requests' beforehand and doesn't specify any problem.

problem will be caused:
- the one which needs 'requests==latest' will have some error because of using that old version of requests

**Comment by natea** [comment]
Fixed.

**Comment by natea** [comment]
The Python package that needed that particular version of requests was dotcloud:
https://github.com/dotcloud/dotcloud-cli/blob/master/setup.py#L56
